// Location actions
export const CHANGE_LOCATION = 'CHANGE_LOCATION';

// Sidebar actions
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

// Map actions
export const CHANGE_RADIUS_TYPE = 'CHANGE_RADIUS_TYPE';
export const CHANGE_RADIUS = 'CHANGE_RADIUS';

// Hospital actions
export const GET_HOSPITALS_REQUESTED = 'GET_HOSPITALS_REQUESTED';
export const GET_HOSPITALS_REJECTED = 'GET_HOSPITALS_REJECTED';
export const GET_HOSPITALS_FULFILLED = 'GET_HOSPITALS_FULFILLED';

// Session actions
export const CLOSE_SESSION_MODAL = 'CLOSE_SESSION_MODAL';
export const LOGIN_SESSION_MODAL = 'LOGIN_SESSION_MODAL';
export const REGISTER_SESSION_MODAL = 'REGISTER_SESSION_MODAL';
